
development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: imjuve_development
  pool: 5
  username: root
  password: 

staging:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: imjuve_development
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: imjuve_development
  pool: 5
  username: root
  password:
  socket: /tmp/mysql.sock

